### PR TITLE
Cap organ slim integration

### PR DESCRIPTION
**Pull request by ubyndr**
Changes related with this comment https://github.com/kharchenkolab/cap-pipeline-config/issues/46#issuecomment-1127903232

> - [ ] Add to triplestore loading config (GitHub raw URL) : https://github.com/kharchenkolab/cap-pipeline-config/blob/main/config/collectdata/vfb_fullontologies.txt
>  - [ ] Update the script that updates the YAML config to point to our local knowledgeBase
>  - [ ] Update the organ[ SPARQL query](https://github.com/kharchenkolab/cap-pipeline-config/blob/main/config/dumps/sparql/construct_Organ.sparql) to use this new subset

### CODE REVIEW

**Comment by dosumis** [comment]
Looks good, but having looked at this again, I think we should tweak the pattern.  Removing the 'cell' clause would allow this to tag all parts of each organ - which may come in handy for boosting or mapping later. We can still identify cells via the 'animal cell' tag.  Also, there are some cases where cell types overlap the specified 'organ', so we could change the generated DL to:

RO:0002131 some X (where X is an organ term).

**Comment by dosumis** [comment]
(Happy to do tweak to DL query in a second PR if you want to get this merged and run the pipeline)

**Comment by ubyndr** [comment]
I have done this couple of weeks ago, 1-2 weeks ago, just realized that I haven't committed the changes.

**Comment by ubyndr** [comment]
> (Happy to do tweak to DL query in a second PR if you want to get this merged and run the pipeline)

As I stated in the previous comment I have re-run the pipeline with this config. I can merge this one and we can continue with a new branch/PR

**Comment by ghost** [comment]
> > (Happy to do tweak to DL query in a second PR if you want to get this merged and run the pipeline)
> 
> As I stated in the previous comment I have re-run the pipeline with this config. I can merge this one and we can continue with a new branch/PR

Hi, @ubyndr, for clarification, have you already done the work in this ticket: https://github.com/kharchenkolab/cap-pipeline-config/issues/59 ?

**Comment by ubyndr** [comment]
> Hi, @ubyndr, for clarification, have you already done the work in this ticket: #59 ?

Hi @bvarner-ebi. No, I haven't done anything about #59. Closing this PR now.

**Pull request merged**
