### PR TITLE
Fixes #10 Adding configuration for Assay field, extension

### LINKED ISSUE #10: Add configuration for Assay field
This can be done with a list of EFO assay terms.  Check suggested terms on Confluence / confirm with Evan.

### PR DESCRIPTION
**Pull request by ghost**
Per https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/2.0.0/schema.md#assay_ontology_term_id, adding the following:

10x 5' v1 ["EFO:0011025"](http://www.ebi.ac.uk/efo/EFO_0011025)
Smart-seq2 ["EFO:0008931"](http://www.ebi.ac.uk/efo/EFO_0008931)

### CODE REVIEW

**Review by dosumis — APPROVED** [review]

**Comment by ubyndr** [comment]
This should have been merge to development not main.

**Comment by ghost** [comment]
> This should have been merge to development not main.

Sorry. @ubyndr. Is there an easy way to fix this?

**Comment by ubyndr** [comment]
I have added these 
```
10x 5' v1 ["EFO:0011025"](http://www.ebi.ac.uk/efo/EFO_0011025)   
Smart-seq2 ["EFO:0008931"](http://www.ebi.ac.uk/efo/EFO_0008931)
```
to development branch. You should update your development branch for further updates :)

**Comment by evanbiederstedt** [comment]
Screen Shot 2022-04-25 at 3 58 11 PM

Before merging, it's possible to select a different branch. 

Anyways, I'm writing to approve.

**Pull request merged**
